#!/bin/bash
# postrm script for mahara
#
# see: dh_installdeb(1)

set -e

#DEBHELPER#

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

. /usr/share/moodle-base/confmodule

case "$1" in
    purge)
        restart_apache2;

        rm -Rf /var/log/sitelogs/moodle-site-otagounifom
        [ -d /var/lib/sitedata/moodle-site-otagounifom ] && echo "NOTE: purge does _not_ remove /var/lib/sitedata/moodle-site-otagounifom or the database, you must do this yourself if you really want to!"
    ;;
    remove)
        restart_apache2;
    ;;
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0



